### ISSUE TITLE
Doesn't Work with Raspberry Pi 3

### ISSUE THREAD

**Issue by wboling** [resin-io-projects/simple-server-node#8]
Seeing some errors pushing this to a cluster of Pi3s.  Getting this:

`Failed to start application 'registry.resin.io/test/ea51fe33f7cac8af562919a5e1caed75235229f6' due to 'Application architecture incompatible with raspberrypi3: exec format error'`

**Comment by shaunmulligan** [comment]
@wboling what version of resinOS are you running? It's strange that you would get this error since the resin.io builder should select and build the correct architecture container for the RPI3. If you can give me a bit more info on your set up, I can try reproduce it.

**Comment by wboling** [comment]
I got it finally.  I just deployed it again and it worked.  I think something may have been corrupted in my git clone.  All is working fine!
